---
# handlers file for bamboo
- name: restart bamboo
  service: name=bamboo state=restarted

- name: reload bamboo
  service: name=bamboo state=reloaded

# nginx
- name: restart nginx
  service: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  service: name=nginx state=reloaded
